### ISSUE TITLE
bug: npm run dev failing in windows

### ISSUE THREAD

**Issue by HarshDobariya79** [LJOSC/community-manager-bot#19]
### Description
- `npm run dev` command need to work on **Windows**, **Linux** as well as **MacOS**.

### Current Behavior
- The command fails for Windows machines.

### Desired Behavior
- The command should work on all Windows, Linux and MacOS environments.

### Hints
- We can remove passing the environment in [dev](https://github.com/LJOSC/community-manager-bot/blob/ea261dde6ac3202757f69c86443b22bf42327c18/package.json#L7C13-L7C33) script since the the default environment is development only.

**Comment by het4399** [comment]
Hey,Can i work on this?😁

**Comment by HarshDobariya79** [comment]
> Hey,Can i work on this?😁

Go ahead @het4399.
